# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d4d9c418405ae943b7cb0338600ea1ce37e37cc53a1b2d51583aa76db88ed040e40b152acec88a79a7532537ab1445895cb32992b176251faa35a24ee1c337a

test:
  secret_key_base: 26ef7964461165f9959165fa638256d92f109381bf4859b61d20d3a986ddd7b7e4cf6d122cc035a52d9784af26b96ac7a1aed28edb1d421f7b43b078e5cadeef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
